Updated ModelUpdatingCest and Create
hiqdev/hipanel-module-stock pull request #110
Opened 2021-05-22 07:29 UTC by Drakorgaur

2021-05-22 11:20 UTC, hiqsol commented on tests/acceptance/manager/ModelUpdatingCest.php
> +        $I->wait(5);
@strorch  как-то можно дождаться реального события, а не по времени?

2021-05-22 11:22 UTC, hiqsol approved these changes

2021-05-22 14:21 UTC, Drakorgaur commented on tests/acceptance/manager/ModelUpdatingCest.php
> +        $I->wait(5);
Мой косяк, я смотрел что там происходит и забыл удалить строчку

2021-05-24 07:02 UTC, strorch requested changes

2021-05-24 07:02 UTC, strorch commented on tests/_support/Page/model/Create.php
> +        $I->click("//a[contains(text(), 'Update')]");
```suggestion
        $I->click('Update');
```

2021-05-24 07:02 UTC, strorch commented on tests/_support/Page/model/Create.php
> +        $tempValue = 'UPD_TEST' . $newModelData['uid'];
`UPD_TEST` треба винести в метод провайдер

2021-05-24 07:02 UTC, strorch commented on tests/_support/Page/model/Create.php
> +        (new Input($I, "//input[@value='".$newModelData['partno']."']"))
```suggestion
        (new Input($I, "//input[@value='{$newModelData['partno']}']"))
```

2021-05-24 10:05 UTC, closed without merging