Feature, add fast move to part section
hiqdev/hipanel-module-stock pull request #117
Opened 2021-07-07 17:09 UTC by tafid

2021-07-08 07:51 UTC, strorch requested changes

2021-07-08 07:51 UTC, strorch commented on src/actions/FastMoveAction.php
> +            if ($controller->request->isPost && $form->load($controller->request->post())) {
$form->validate() треба ще

2021-07-08 07:51 UTC, strorch commented on src/actions/FastMoveAction.php
> +            if ($controller->request->isPost && $form->load($controller->request->post())) {
а при яких кейсах виникає ексепшн?

2021-07-08 07:51 UTC, strorch commented on src/forms/FastMoveForm.php
> +        $servers = $this->resolveDestinations($destinations);
може це краще на стороні апі робить?

2021-07-09 08:33 UTC, strorch approved these changes

2021-07-09 13:24 UTC, SilverFire requested changes

2021-07-09 13:24 UTC, SilverFire commented on src/controllers/PartController.php
> +                'success' => Yii::t('hipanel:stock', 'Parts has been updated'),
https://puzzle-english.com/directory/present-perfect

Откатывай назад :)

2021-07-09 13:24 UTC, SilverFire commented on src/messages/ru/hipanel:stock.php
> +    'Type server names using a space, comma or on a new line' => 'Введите имена серверов через пробел, запятую или с новой строки.',
```suggestion
    'Type server names, delimited with a space, comma or a new line' => 'Введите имена серверов через пробел, запятую или с новой строки.',
```

Ато полчается "Введите имена серверов пробелом, запятой ...."

2021-07-09 13:24 UTC, SilverFire commented on src/widgets/FastMoveModal.php
> +        if (!Yii::$app->user->can('part.create')) {
```suggestion
        if (!Yii::$app->user->can('move.create')) {
```

2021-07-09 17:21 UTC, SilverFire approved these changes

2021-07-09 17:21 UTC, merged