Made test uniq - added method for creation parts
hiqdev/hipanel-module-stock pull request #122
Opened 2021-07-22 09:09 UTC by Drakorgaur

![image](https://user-images.githubusercontent.com/83531949/126615319-a70d19d8-d304-447c-86e0-1ef72258d018.png)

2021-08-05 07:31 UTC, strorch requested changes

2021-08-05 07:31 UTC, strorch commented on tests/acceptance/manager/PartsSellingCest.php
> +        $this->sellData = $this->getSellData();
треба переробить на дата провайдер

2021-08-05 07:31 UTC, strorch commented on tests/acceptance/manager/PartsSellingCest.php
> +            $page->fillPartFields($this->getPartData());
треба переробить на дата провайдер

2021-08-05 07:31 UTC, strorch commented on tests/acceptance/manager/PartsSellingCest.php
> +        foreach ($this->sellData['prices'] as $part) {
а чого в ключі прайсес лежать парти

2021-08-05 07:31 UTC, strorch commented on tests/acceptance/manager/PartsSellingCest.php
> +    public function ensureICanCreatePart(Manager $I): void
уже єсть PartsCreationCest, перейменуй його краще в PartsCest і зроби там методи по створенню і продажі парта, бо куча тестів створюють кучу партов

2021-08-06 07:28 UTC, strorch requested changes
а шо це за блоксхема? ти її для пр-а малював чи вона з доків взялась?

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +            'sellInfo' => [
```suggestion
            [
```

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +            ]
```suggestion
            ],
```

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +                'time'      => (new \DateTime())->format('Y-m-d H:i'),
```suggestion
                'time'      => (new DateTime())->format('Y-m-d H:i'),
```
а зверху `use DateTime;`

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +    protected array $sellData;
не думаю, що це поле треба, треба брать з датапровайдера

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +    protected Create $createPage;
видали пліз це з _before і залиш тільки в тих місцях де цей клас треба

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
>      protected $testOrderData;
і заміни оце тож на дата провайдер

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +        $partIndex      = new IndexPage($I);
```suggestion
        $partIndex = new IndexPage($I);
```

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +        $sellModal      = new SellModalWindow($I);
```suggestion
        $sellModal = new SellModalWindow($I);
```

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +        $I->seeNumberOfElements('tr table  tr[data-key]', count($this->sellData['prices']));
дата провайдер

2021-08-06 07:28 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +        $billPage = new IndexPage($I);
перенеси цей метод може в цей IndexPage

2021-08-07 08:54 UTC, Drakorgaur commented on tests/acceptance/manager/PartsCest.php
> +            'sellInfo' => [
> а шо це за блоксхема? ти її для пр-а малював чи вона з доків взялась?

Для ПР

2021-08-07 09:05 UTC, Drakorgaur commented on tests/acceptance/manager/PartsCest.php
> +                'time'      => (new \DateTime())->format('Y-m-d H:i'),
Не працюэ без бэкслеша

2021-08-07 09:26 UTC, Drakorgaur commented on tests/acceptance/manager/PartsCest.php
>      protected $testOrderData;
protected $testOrderData вообще не использовался в тесте, но я побрезгал убирать. В этом коммите убираю. 
![image](https://user-images.githubusercontent.com/83531949/128595666-a4f1bcab-62e3-4efa-89d4-bf04d23c5ec6.png)

2021-08-09 10:11 UTC, strorch commented on tests/acceptance/manager/PartsCest.php
> +                'time'      => (new \DateTime())->format('Y-m-d H:i'),
> а зверху use DateTime;

вот же в коменті вище писав

2021-08-09 10:13 UTC, strorch approved these changes

2021-08-09 10:14 UTC, merged