add dc location
hiqdev/hipanel-module-stock pull request #126
Opened 2021-12-28 12:23 UTC by bladeroot

2021-12-29 09:16 UTC, SilverFire requested changes

2021-12-29 09:16 UTC, SilverFire commented on src/models/Part.php
> +            'device_location' => Yii::t('hipanel:stock', 'DC location'),
Перевод на русский

2021-12-31 14:06 UTC, tafid approved these changes

2022-01-06 08:49 UTC, hiqsol commented on src/messages/ru/hipanel:stock.php
> +    'DC location' -> 'Распооложение',
```suggestion
    'DC location' -> 'Расположение',
```

2022-01-06 08:52 UTC, hiqsol approved these changes

2022-01-06 08:52 UTC, merged