fixed src_id in actions with parts moving
hiqdev/hipanel-module-stock pull request #85
Opened 2020-10-26 14:15 UTC by strorch

2020-10-26 17:11 UTC, SilverFire requested changes
Мутировать модель нельзя

2020-10-29 12:31 UTC, tafid approved these changes

2020-10-29 13:25 UTC, SilverFire requested changes

2020-10-29 13:25 UTC, SilverFire commented on src/messages/ru/hipanel:stock.php
> +    'Part has been replaced' => 'Детали заменены',
```suggestion
    'Part has been replaced' => 'Деталь заменена',
```

2020-10-29 13:25 UTC, SilverFire approved these changes

2020-10-29 13:25 UTC, merged